<a href="https://colab.research.google.com/github/jaymehta1444/RJVH_IPD/blob/main/IPD1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
main_data_30_yrs = pd.read_csv('/content/India Agriculture Crop Production.csv')
main_data_30_yrs.head()

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
0,Andaman and Nicobar Islands,NICOBARS,Arecanut,2001-02,Kharif,1254.0,Hectare,2061.0,Tonnes,1.643541
1,Andaman and Nicobar Islands,NICOBARS,Arecanut,2002-03,Whole Year,1258.0,Hectare,2083.0,Tonnes,1.655803
2,Andaman and Nicobar Islands,NICOBARS,Arecanut,2003-04,Whole Year,1261.0,Hectare,1525.0,Tonnes,1.209358
3,Andaman and Nicobar Islands,NORTH AND MIDDLE ANDAMAN,Arecanut,2001-02,Kharif,3100.0,Hectare,5239.0,Tonnes,1.690000
4,Andaman and Nicobar Islands,SOUTH ANDAMANS,Arecanut,2002-03,Whole Year,3105.0,Hectare,5267.0,Tonnes,1.696296

In [ ]:
maharashtra_main_data = main_data_30_yrs[main_data_30_yrs['State'] == 'Maharashtra']
maharashtra_main_data.head()

,State,District,Crop,Year,Season,Area,Area Units,Production,Production Units,Yield
22370,Maharashtra,AHMEDNAGAR,Arhar/Tur,2001-02,Kharif,16700.0,Hectare,5400.0,Tonnes,0.323353
22371,Maharashtra,AHMEDNAGAR,Arhar/Tur,2002-03,Kharif,14600.0,Hectare,5700.0,Tonnes,0.390411
22372,Maharashtra,AHMEDNAGAR,Arhar/Tur,2003-04,Kharif,9000.0,Hectare,3000.0,Tonnes,0.333333
22373,Maharashtra,AKOLA,Arhar/Tur,2001-02,Kharif,46800.0,Hectare,41600.0,Tonnes,0.888889
22374,Maharashtra,AKOLA,Arhar/Tur,2002-03,Kharif,46500.0,Hectare,42100.0,Tonnes,0.905376

In [ ]:
maharashtra_main_data = maharashtra_main_data.drop(['State', 'Area Units','Production', 'Production Units'], axis=1)
maharashtra_main_data.head()

         District       Crop     Year  Season     Area     Yield
22370  AHMEDNAGAR  Arhar/Tur  2001-02  Kharif  16700.0  0.323353
22371  AHMEDNAGAR  Arhar/Tur  2002-03  Kharif  14600.0  0.390411
22372  AHMEDNAGAR  Arhar/Tur  2003-04  Kharif   9000.0  0.333333
22373       AKOLA  Arhar/Tur  2001-02  Kharif  46800.0  0.888889
22374       AKOLA  Arhar/Tur  2002-03  Kharif  46500.0  0.905376

In [ ]:
maharashtra_main_data = maharashtra_main_data.reset_index(drop=True)
maharashtra_main_data.head()

     District       Crop     Year  Season     Area     Yield
0  AHMEDNAGAR  Arhar/Tur  2001-02  Kharif  16700.0  0.323353
1  AHMEDNAGAR  Arhar/Tur  2002-03  Kharif  14600.0  0.390411
2  AHMEDNAGAR  Arhar/Tur  2003-04  Kharif   9000.0  0.333333
3       AKOLA  Arhar/Tur  2001-02  Kharif  46800.0  0.888889
4       AKOLA  Arhar/Tur  2002-03  Kharif  46500.0  0.905376

In [ ]:
maharashtra_main_data.shape

(17922, 6)

In [ ]:
maharashtra_main_data["Season"] = maharashtra_main_data["Season"].apply(lambda x: x.strip())
maharashtra_main_data["Year"] = maharashtra_main_data["Year"].apply(lambda x: x.split('-')[0].strip())
maharashtra_main_data

         District       Crop  Year  Season     Area     Yield
0      AHMEDNAGAR  Arhar/Tur  2001  Kharif  16700.0  0.323353
1      AHMEDNAGAR  Arhar/Tur  2002  Kharif  14600.0  0.390411
2      AHMEDNAGAR  Arhar/Tur  2003  Kharif   9000.0  0.333333
3           AKOLA  Arhar/Tur  2001  Kharif  46800.0  0.888889
4           AKOLA  Arhar/Tur  2002  Kharif  46500.0  0.905376
...           ...        ...   ...     ...      ...       ...
17917      WASHIM      Wheat  2000    Rabi  12800.0  0.968750
17918    YAVATMAL      Wheat  1997    Rabi  18600.0  0.467742
17919    YAVATMAL      Wheat  1998    Rabi  21100.0  1.208531
17920    YAVATMAL      Wheat  1999    Rabi  24200.0  1.190083
17921    YAVATMAL      Wheat  2000    Rabi  17100.0  1.105263

[17922 rows x 6 columns]

In [ ]:
maharashtra_main_data['District'].value_counts()

District
AHMEDNAGAR         697
PUNE               689
SATARA             667
SOLAPUR            662
LATUR              660
PARBHANI           656
BEED               652
OSMANABAD          652
NANDED             652
NASHIK             648
SANGLI             632
AURANGABAD         608
JALNA              595
DHULE              593
KOLHAPUR           593
NANDURBAR          586
BULDHANA           585
JALGAON            559
AMRAVATI           547
HINGOLI            546
NAGPUR             537
CHANDRAPUR         478
AKOLA              473
YAVATMAL           469
GADCHIROLI         448
WASHIM             446
WARDHA             421
BHANDARA           394
THANE              366
GONDIA             342
RAIGAD             332
RATNAGIRI          319
SINDHUDURG         319
PALGHAR             96
MUMBAI SUBURBAN      2
MUMBAI               1
Name: count, dtype: int64

In [ ]:
maharashtra_main_data = maharashtra_main_data[maharashtra_main_data['District'] != 'MUMBAI']
maharashtra_main_data = maharashtra_main_data[maharashtra_main_data['District'] != 'MUMBAI SUBURBAN']
maharashtra_main_data['District'].value_counts()

District
AHMEDNAGAR    697
PUNE          689
SATARA        667
SOLAPUR       662
LATUR         660
PARBHANI      656
OSMANABAD     652
NANDED        652
BEED          652
NASHIK        648
SANGLI        632
AURANGABAD    608
JALNA         595
KOLHAPUR      593
DHULE         593
NANDURBAR     586
BULDHANA      585
JALGAON       559
AMRAVATI      547
HINGOLI       546
NAGPUR        537
CHANDRAPUR    478
AKOLA         473
YAVATMAL      469
GADCHIROLI    448
WASHIM        446
WARDHA        421
BHANDARA      394
THANE         366
GONDIA        342
RAIGAD        332
RATNAGIRI     319
SINDHUDURG    319
PALGHAR        96
Name: count, dtype: int64

In [ ]:
maharashtra_main_data['Crop'].value_counts()

Crop
Maize                  1572
Groundnut              1232
Sunflower              1222
Jowar                  1189
Sesamum                 931
Rice                    874
Small millets           784
Urad                    742
Moong(Green Gram)       737
Arhar/Tur               731
Gram                    709
Wheat                   680
Other Kharif pulses     672
Soyabean                617
Sugarcane               602
Other Rabi pulses       597
Cotton(lint)            596
Bajra                   491
Rapeseed &Mustard       473
Niger seed              431
Safflower               425
Castor seed             422
Linseed                 347
Other Cereals           322
Ragi                    273
other oilseeds          125
Other Summer Pulses      61
Banana                   28
Onion                    26
Tobacco                   8
Name: count, dtype: int64

## Selecting the crops that are widely grown currently, and those that have good potential

In [ ]:
crops_to_drop = ['Tobacco', 'Onion', 'Banana', 'Other Summer Pulses', 'other oilseeds', 'Ragi', 'Other Cereals', 'Linseed', 'Castor seed', 'Safflower', 'Niger seed', 'Bajra', 'Other Rabi pulses', 'Other Kharif pulses', 'Wheat']
maharashtra_main_data.drop(maharashtra_main_data[maharashtra_main_data['Crop'].isin(crops_to_drop)].index, inplace = True)
maharashtra_main_data['Crop'].value_counts()

Crop
Maize                1572
Groundnut            1232
Sunflower            1222
Jowar                1189
Sesamum               931
Rice                  874
Small millets         784
Urad                  742
Moong(Green Gram)     737
Arhar/Tur             731
Gram                  709
Soyabean              617
Sugarcane             602
Cotton(lint)          596
Rapeseed &Mustard     473
Name: count, dtype: int64

In [ ]:
maharashtra_main_data.head()

     District       Crop  Year  Season     Area     Yield
0  AHMEDNAGAR  Arhar/Tur  2001  Kharif  16700.0  0.323353
1  AHMEDNAGAR  Arhar/Tur  2002  Kharif  14600.0  0.390411
2  AHMEDNAGAR  Arhar/Tur  2003  Kharif   9000.0  0.333333
3       AKOLA  Arhar/Tur  2001  Kharif  46800.0  0.888889
4       AKOLA  Arhar/Tur  2002  Kharif  46500.0  0.905376

In [ ]:
def clean_crop_name(crop):
    if crop == 'Small millets':
        return 'Small Millets'
    elif crop == 'Moong(Green Gram)':
        return 'Moong'
    elif crop == 'Arhar/Tur':
        return 'Tur'
    elif crop == 'Cotton(lint)':
        return 'Cotton'
    elif crop == 'Rapeseed &Mustard':
        return 'Mustard'
    else:
        return crop

In [ ]:
maharashtra_main_data['Crop'] = maharashtra_main_data['Crop'].apply(clean_crop_name)

In [ ]:
maharashtra_main_data

         District  Crop  Year  Season     Area     Yield
0      AHMEDNAGAR   Tur  2001  Kharif  16700.0  0.323353
1      AHMEDNAGAR   Tur  2002  Kharif  14600.0  0.390411
2      AHMEDNAGAR   Tur  2003  Kharif   9000.0  0.333333
3           AKOLA   Tur  2001  Kharif  46800.0  0.888889
4           AKOLA   Tur  2002  Kharif  46500.0  0.905376
...           ...   ...   ...     ...      ...       ...
17807      WASHIM  Urad  2000  Kharif  61000.0  0.439344
17808    YAVATMAL  Urad  1997  Kharif  23300.0  0.240343
17809    YAVATMAL  Urad  1998  Kharif  24100.0  0.539419
17810    YAVATMAL  Urad  1999  Kharif  23800.0  0.756303
17811    YAVATMAL  Urad  2000  Kharif  25300.0  0.498024

[13011 rows x 6 columns]

In [ ]:
maharashtra_main_data.isna().sum()

District    0
Crop        0
Year        0
Season      0
Area        0
Yield       0
dtype: int64

In [ ]:
weather_data = pd.read_csv('/content/weather_data.csv')
weather_data.head()

     District  year  season  temperature_2m_mean  rain_sum
0  AHMEDNAGAR  1997  Autumn            22.646185    49.500
1  AHMEDNAGAR  1997  Kharif            23.998425   112.450
2  AHMEDNAGAR  1997    Rabi            21.448471     9.375
3  AHMEDNAGAR  1997  Summer            27.624930     8.750
4  AHMEDNAGAR  1998  Autumn            21.595100    66.500

In [ ]:
weather_data.columns = ['District', 'Year', 'Season', 'Temperature', 'Rainfall']
weather_data["Year"] = weather_data["Year"].apply(lambda x: f"{x}")
weather_data["District"] = weather_data["District"].apply(lambda x: x.strip().upper())
weather_data.sort_values(by = ["District", "Year", "Season"], inplace = True)
weather_data

        District  Year  Season  Temperature    Rainfall
0     AHMEDNAGAR  1997  Autumn    22.646185   49.500000
1     AHMEDNAGAR  1997  Kharif    23.998425  112.450000
2     AHMEDNAGAR  1997    Rabi    21.448471    9.375000
3     AHMEDNAGAR  1997  Summer    27.624930    8.750000
4     AHMEDNAGAR  1998  Autumn    21.595100   66.500000
...          ...   ...     ...          ...         ...
2847    YAVATMAL  2018  Summer    34.262380   10.600000
2848    YAVATMAL  2019  Autumn    24.885715   42.749996
2849    YAVATMAL  2019  Kharif    28.049831  284.575000
2850    YAVATMAL  2019    Rabi    24.421940    5.400001
2851    YAVATMAL  2019  Summer    35.332703    0.500000

[2944 rows x 5 columns]

In [ ]:
merged_df = pd.merge(maharashtra_main_data, weather_data, how = 'left', on = ['District', 'Year', 'Season'])
merged_df

,District,Crop,Year,Season,Area,Yield,Temperature,Rainfall
0,AHMEDNAGAR,Tur,2001,Kharif,16700.0,0.323353,23.508500,151.87500
1,AHMEDNAGAR,Tur,2002,Kharif,14600.0,0.390411,23.652390,124.05000
2,AHMEDNAGAR,Tur,2003,Kharif,9000.0,0.333333,23.707798,127.42500
3,AKOLA,Tur,2001,Kharif,46800.0,0.888889,27.150816,178.65000
4,AKOLA,Tur,2002,Kharif,46500.0,0.905376,27.332598,280.80002
...,...,...,...,...,...,...,...,...
13006,WASHIM,Urad,2000,Kharif,61000.0,0.439344,25.681866,243.42500
13007,YAVATMAL,Urad,1997,Kharif,23300.0,0.240343,27.584457,213.05000
13008,YAVATMAL,Urad,1998,Kharif,24100.0,0.539419,27.739752,232.02500
13009,YAVATMAL,Urad,1999,Kharif,23800.0,0.756303,26.204884,225.75000
13010,YAVATMAL,Urad,2000,Kharif,25300.0,0.498024,26.450370,280.62500

In [ ]:
merged_df.isna().sum()

District         0
Crop             0
Year             0
Season           0
Area             0
Yield            0
Temperature    870
Rainfall       870
dtype: int64

In [ ]:
merged_df.dropna(inplace=True)

In [ ]:
merged_df.isna().sum()

District       0
Crop           0
Year           0
Season         0
Area           0
Yield          0
Temperature    0
Rainfall       0
dtype: int64

In [ ]:
merged_df.shape

(12141, 8)

In [ ]:
cols = list(merged_df.columns)
cols.insert(len(cols)-1, cols.pop(cols.index('Yield')))
merged_df = merged_df.loc[:, cols]
merged_df.head()

     District Crop  Year  Season     Area  Temperature   Rainfall     Yield
0  AHMEDNAGAR  Tur  2001  Kharif  16700.0    23.508500  151.87500  0.323353
1  AHMEDNAGAR  Tur  2002  Kharif  14600.0    23.652390  124.05000  0.390411
2  AHMEDNAGAR  Tur  2003  Kharif   9000.0    23.707798  127.42500  0.333333
3       AKOLA  Tur  2001  Kharif  46800.0    27.150816  178.65000  0.888889
4       AKOLA  Tur  2002  Kharif  46500.0    27.332598  280.80002  0.905376

In [ ]:
merged_df['Year'] = pd.to_datetime(merged_df['Year'], format='%Y')

In [ ]:
merged_df.to_csv('maharashtra_crop_weather.csv', index=False)